version: "3"
services:
  postgres:
    image: postgres:17.5-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgraphql
  mariadb:
    image: mariadb:11.7
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: postgraphql
